### ISSUE TITLE
Proposal 

### ISSUE THREAD

**Issue by la-niina** [Saeed-Pooyanfar/Xray#1]
Can we work together to make a better VPN , with the V2RAY ,xtls , udpgw, ssh , sll, tls , psiphon am familiar with most of them but not good at the core implementation I am good at UI design and other code we can write it in kotlin compose or jetpack. my email is la.niina.me@gmail.com if you agree

**Comment by Saeed-Pooyanfar** [comment]
Thanks for your interest in my android Xray client  
I have no plan to add support for ssh, udpgw, ...  
This app is a client for `XTLS/Xray-core` only and i want to keep it simple as possible
